POST http://localhost:5000/api/users/register
Content-Type: application/json

{
    "email":"asd@asd.com",
    "password":"asd",
    "passwordCheck":"asd",
    "displayName":"fki" 
}

###

POST http://localhost:5000/api/users/login
Content-Type: application/json

{
    "email":"asd@asd.com",
    "password":"asd"
}

###
POST http://localhost:5000/api/users/tokenIsvalid
Content-Type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmMzBiODU3Y2IzY2ZjMDhkMDY5YjgyMSIsImlhdCI6MTU5NzAyODQ0OX0.BMwNCb746wRqy0XlpmFujVngsXGS3BeFRkiLWu1zT2Q

###
GET http://localhost:5000/api/users/
Content-Type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmMzBiODU3Y2IzY2ZjMDhkMDY5YjgyMSIsImlhdCI6MTU5NzAyODQ0OX0.BMwNCb746wRqy0XlpmFujVngsXGS3BeFRkiLWu1zT2Q

###
DELETE  http://localhost:5000/api/users/delete
Content-Type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmMzBiODU3Y2IzY2ZjMDhkMDY5YjgyMSIsImlhdCI6MTU5NzAyODQ0OX0.BMwNCb746wRqy0XlpmFujVngsXGS3BeFRkiLWu1zT2Q