POST http://localhost:5000/api/users/register
Content-Type: application/json

{
    "userName":"fki" ,
    "password":"asd",
    "confirmPassword":"asd"
}

###
POST http://localhost:5000/api/users/login
Content-Type: application/json

{
    "userName":"fki" ,
    "password":"asd"
}

###
POST http://localhost:5000/api/users/tokenIsvalid
Content-Type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmMzE1ODNmM2RkMTM0MjJkOGU5NmFhNyIsInVzZXJOYW1lIjoiZmtpIiwiaWF0IjoxNTk3MjQyOTU2fQ.QPYAV5mYkKv2aF5YT2WqWWYbh4_1ScVtNAm63bVvGLc

###
GET http://localhost:5000/api/users/
Content-Type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmMzE1ODNmM2RkMTM0MjJkOGU5NmFhNyIsInVzZXJOYW1lIjoiZmtpIiwiaWF0IjoxNTk3MjQyOTU2fQ.QPYAV5mYkKv2aF5YT2WqWWYbh4_1ScVtNAm63bVvGLc

###
DELETE  http://localhost:5000/api/users/delete
Content-Type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmMzE1ODNmM2RkMTM0MjJkOGU5NmFhNyIsInVzZXJOYW1lIjoiZmtpIiwiaWF0IjoxNTk3MjI3MTE4fQ.rwd_MOJsbtwc3MzqSTwuG9E0B8qWUfpAwlb2vPOtmp8


# ***********************************


###
POST http://localhost:5000/api/doctors/register
Content-Type: application/json

{
    "firstName":"farhan",
    "lastName":"irani",
    "userName":"adocfki" ,
    "email":"afarhanirani@gmail.com",
    "phoneNumber":"12693123123",
    "url":"url.com",
    "password":"asd",
    "confirmPassword":"asd"
}


###
POST http://localhost:5000/api/doctors/login
Content-Type: application/json

{
    "userName":"docfki" ,
    "password":"asd"
}

###
GET http://localhost:5000/api/doctors/
Content-Type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmMzI2MjNmMmY5YTkwM2E0YzBlODllZCIsImlhdCI6MTU5NzEzODM1N30.Wze5dTw4MepPsiMJ4iwJW_WvQGADpG5TYOXh0AmHPcE
