POST http://localhost:5000/api/forum/create 
Content-Type: application/json

{
    "title":"Mental Health",
    "desc":"A safe place to discuss any Mental Health problems"
}

###
GET http://localhost:5000/api/forum

###
GET http://localhost:5000/api/forum/5f36911a1ef4f52c7cce8d15
